### PR TITLE
Add more fields to the Resource and Feedback models. #29

### PR DESCRIPTION
**Pull request by jrp114**

### CODE REVIEW

**Comment by jrp114** [comment]
I was able to use the strptime function to adjust the assertion data, but I have not yet been able to adjust the datetimefield model object return data to match yet.
AssertionError: datetime.datetime(2018, 7, 9, 14, 25, 18, 207147) != datetime.datetime(2018, 7, 9, 14, 25)

**Comment by jastr945** [comment]
Actually, you could just do: 
```
self.assertEqual(self.resource1.updated_at.replace(microsecond=0), self.now.replace(microsecond=0))
self.assertNotEqual(self.resource1.created_at.replace(microsecond=0), self.past.replace(microsecond=0))
```
:)
And if you remove "auto_now_add=True" from "created_at" field on the Resource model, you should be able to change the second test to:
```
self.assertEqual(self.resource1.created_at.replace(microsecond=0), self.past.replace(microsecond=0))
```
We want our test Resource instance to be created a day ago and updated now. self.resource1.created_at should be always equal to self.past, right?

There is another reason why we should definitely remove  "auto_now_add=True" from "created_at" model field. Some of our imported datasets come with created_at fields. We don't want to override them with datetime.now. We also want to keep these fields editable. You could try and change the model fields the following way:
```
from django.utils import timezone

created_at = models.DateTimeField(default=timezone.now, null=True)
updated_at = models.DateTimeField(default=timezone.now, null=True)
```
Let us know if that works, or if you run into any issues.

**Comment by jrp114** [comment]
This works for all except the api tests. Is there a way to manipulate the created_at and updated_at elements like above for the json entries?

**Comment by jastr945** [comment]
What if you change the DateTime format on the Resource serializer? 
```
class ResourceSerializer(serializers.ModelSerializer):
    feedback = FeedbackSerializer(many=True)
    created_at = serializers.DateTimeField(format="%Y-%m-%d %H:%M")
    updated_at = serializers.DateTimeField(format="%Y-%m-%d %H:%M")
    
class Meta: 
    ...
```
If this doesn't help, please paste the error messages displayed.

**Comment by jrp114** [comment]
Thanks for the info! Should be good now ;)

**Pull request merged**
